import React from "react";
import { Header } from "../components/Header";
import { Container } from "../components/Container";
import Footer from "../components/Footer";
import { Link } from "react-router-dom";
import { useUser } from "../hooks/user";

function Landing() {
  const { user } = useUser();
  return (
    <div>
      <Header />
      <section class="relative bg-[#151522] min-h-screen">
        <svg
          class="absolute w-full"
          fill="none"
          viewBox="0 0 960 637"
          height="100%"
          width="100%"
          xmlns="http://www.w3.org/2000/svg"
        >
          <g filter="url(#filter0_f_1_167)">
            <ellipse
              cx="479.5"
              cy="318.5"
              fill="#2463eb"
              fill-opacity="0.5"
              rx="118.5"
              ry="118.5"
              transform="rotate(-90 479.5 318.5)"
            ></ellipse>
          </g>
          <mask
            height="573"
            id="mask0_1_167"
            maskUnits="userSpaceOnUse"
            style={{ maskType: "alpha" }}
            width="960"
            x="0"
            y="32"
          >
            <rect
              height="573"
              width="960"
              y="32"
              fill="url(#paint0_radial_1_167)"
            ></rect>
          </mask>
          <g mask="url(#mask0_1_167)">
            <rect
              height="79"
              width="79"
              y="41.5"
              stroke="white"
              x="123.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="41.5"
              stroke="white"
              x="202.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="41.5"
              stroke="white"
              x="281.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="41.5"
              stroke="white"
              x="360.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="41.5"
              stroke="white"
              x="439.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="41.5"
              stroke="white"
              x="518.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="41.5"
              stroke="white"
              x="597.5"
              fill="white"
              fill-opacity="0.25"
            ></rect>
            <rect
              height="79"
              width="79"
              y="41.5"
              stroke="white"
              x="676.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="41.5"
              stroke="white"
              x="755.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="120.5"
              stroke="white"
              x="123.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="120.5"
              stroke="white"
              x="202.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="120.5"
              stroke="white"
              x="281.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="120.5"
              stroke="white"
              x="360.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="120.5"
              stroke="white"
              x="439.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="120.5"
              stroke="white"
              x="518.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="120.5"
              stroke="white"
              x="597.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="120.5"
              stroke="white"
              x="676.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="120.5"
              stroke="white"
              x="755.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="199.5"
              stroke="white"
              x="123.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="199.5"
              stroke="white"
              x="202.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="199.5"
              stroke="white"
              x="281.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="199.5"
              stroke="white"
              x="360.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="199.5"
              stroke="white"
              x="439.5"
              fill="white"
              fill-opacity="0.25"
            ></rect>
            <rect
              height="79"
              width="79"
              y="199.5"
              stroke="white"
              x="518.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="199.5"
              stroke="white"
              x="597.5"
              fill="white"
              fill-opacity="0.25"
            ></rect>
            <rect
              height="79"
              width="79"
              y="199.5"
              stroke="white"
              x="676.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="199.5"
              stroke="white"
              x="755.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="278.5"
              stroke="white"
              x="123.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="278.5"
              stroke="white"
              x="202.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="278.5"
              stroke="white"
              x="281.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="278.5"
              stroke="white"
              x="360.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="278.5"
              stroke="white"
              x="439.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="278.5"
              stroke="white"
              x="518.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="278.5"
              stroke="white"
              x="597.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="278.5"
              stroke="white"
              x="676.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="278.5"
              stroke="white"
              x="755.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="357.5"
              stroke="white"
              x="123.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="357.5"
              stroke="white"
              x="202.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="357.5"
              stroke="white"
              x="281.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="357.5"
              stroke="white"
              x="360.5"
              fill="white"
              fill-opacity="0.25"
            ></rect>
            <rect
              height="79"
              width="79"
              y="357.5"
              stroke="white"
              x="439.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="357.5"
              stroke="white"
              x="518.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="357.5"
              stroke="white"
              x="597.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="357.5"
              stroke="white"
              x="676.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="357.5"
              stroke="white"
              x="755.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="436.5"
              stroke="white"
              x="123.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="436.5"
              stroke="white"
              x="202.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="436.5"
              stroke="white"
              x="281.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="436.5"
              stroke="white"
              x="360.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="436.5"
              stroke="white"
              x="439.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="436.5"
              stroke="white"
              x="518.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="436.5"
              stroke="white"
              x="597.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="436.5"
              stroke="white"
              x="676.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="436.5"
              stroke="white"
              x="755.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="515.5"
              stroke="white"
              x="123.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="515.5"
              stroke="white"
              x="202.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="515.5"
              stroke="white"
              x="281.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="515.5"
              stroke="white"
              x="360.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="515.5"
              stroke="white"
              x="439.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="515.5"
              stroke="white"
              x="518.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="515.5"
              stroke="white"
              x="597.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="515.5"
              stroke="white"
              x="676.5"
            ></rect>
            <rect
              height="79"
              width="79"
              y="515.5"
              stroke="white"
              x="755.5"
            ></rect>
          </g>
          <defs>
            <filter
              color-interpolation-filters="sRGB"
              filterUnits="userSpaceOnUse"
              height="637"
              id="filter0_f_1_167"
              width="637"
              x="161"
              y="1.14441e-05"
            >
              <feFlood flood-opacity="0" result="BackgroundImageFix"></feFlood>
              <feBlend
                in="SourceGraphic"
                in2="BackgroundImageFix"
                mode="normal"
                result="shape"
              ></feBlend>
              <feGaussianBlur
                result="effect1_foregroundBlur_1_167"
                stdDeviation="100"
              ></feGaussianBlur>
            </filter>
            <radialGradient
              cx="0"
              cy="0"
              gradientTransform="translate(480 318.5) rotate(90) scale(353.19 591.732)"
              gradientUnits="userSpaceOnUse"
              id="paint0_radial_1_167"
              r="1"
            >
              <stop stop-color="#D9D9D9" stop-opacity="0.2"></stop>
              <stop
                stop-color="#D9D9D9"
                stop-opacity="0"
                offset="0.802083"
              ></stop>
            </radialGradient>
          </defs>
        </svg>
        <div class="relative items-center w-full h-full px-5 py-12 mx-auto max-w-7xl lg:px-16 lg:py-36 md:px-12 ">
          <div class="mx-auto text-center h-full">
            <img
              src="/logo.png"
              alt=""
              className="m-auto w-full max-w-lg p-10 max-sm:p-5"
            />
            <div>
              <p class="text-4xl font-bold tracking-tight text-white md:text-7xl">
                The Heart of the
                <span class="md:block"> Web Developer Community</span>
              </p>
              <p class="max-w-3xl mx-auto mt-8 text-base lg:text-xl text-white/70">
                We’re on a mission to build the world’s best community for web
                developers to share, grow, collaborate, get feedback, expand
                their skills, and get hired.
              </p>
            </div>
            {user ? (
              <div>
                <p class="max-w-3xl mx-auto mt-8 text-base lg:text-xl text-white">
                  Welcome back{" "}
                  <Link
                    to="/profile"
                    className="underline  font-semibold tracking-wide ml-1"
                  >
                    {" "}
                    {user.name}!
                  </Link>
                </p>
                <Link
                  class="mt-5 items-center justify-center focus:outline-none inline-flex text-white hover:bg-[#2463eb]/5 rounded-xl duration-200 focus-visible:outline-black focus-visible:ring-black font-medium hover:text-[#2463eb] lg:w-auto px-6 py-3 text-center w-full bg-[#2463eb]"
                  to={"/craftsshowcase"}
                >
                  Go to Craft land →
                </Link>
              </div>
            ) : (
              <div class="flex flex-col justify-center gap-3 mt-10 sm:flex-row">
                <Link
                  class="items-center justify-center focus:outline-none inline-flex text-white hover:bg-[#2463eb]/5 rounded-xl duration-200 focus-visible:outline-black focus-visible:ring-black font-medium hover:text-[#2463eb] lg:w-auto px-6 py-3 text-center w-full bg-[#2463eb]"
                  to={"/register"}
                >
                  Create new account →
                </Link>
                <Link
                  class="items-center justify-center focus:outline-none inline-flex text-white hover:bg-[#2463eb]/5 rounded-xl duration-200 focus-visible:outline-black focus-visible:ring-black font-medium hover:text-[#2463eb] lg:w-auto px-6 py-3 text-center w-full bg-[#2463eb]/5"
                  to={"/login"}
                >
                  Login to Craft land{" "}
                </Link>
              </div>
            )}
          </div>
          <div class="relative items-center w-full pb-12 mx-auto mt-12 max-w-7xl h-full">
            <iframe
              className="w-full h-[650px]"
              src="https://www.youtube.com/embed/sZOc2Oi-4AE"
              title="Web Crafts Demo"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
              allowFullScreen
            ></iframe>
          </div>
        </div>
      </section>
      <Footer />
    </div>
  );
}

export default Landing;
